# About the Author {-}

Je m'appelle Olivier Gimenez (<https://oliviergimenez.github.io/>). Je suis directeur de recherche au CNRS. Après des études universitaires en mathématiques, j'ai fait une thèse en statistiques pour l'écologie. J'ai passé mon Habilitation à Diriger des Recherches en écologie et évolution. Récemment, je suis retourné sur les bancs de l'université pour m'initier à la sociologie.

J'ai écrit des [articles scientifiques](https://oliviergimenez.github.io/publication/papers/) faisant appel à la statistique bayésienne, et co-écrit avec des collègues britanniques un [livre sur les analyses bayésiennes pour l'écologie des populations](https://oliviergimenez.github.io/publication/books/).

Vous pouvez me retrouver sur Twitter (<https://twitter.com/oaggimenez>), ou bien me contacter via mon adresse email qui s'écrit olivier suivi d'un point puis gimenez, ensuite arobase, puis cefe, suivi d'un point, puis cnrs, suivi d'un point et pour terminer fr.

Tombé dedans quand j'étais petit. Obélix Roger et Astérix JD.  