# Life history {#tradeoffs}

WORK IN PROGRESS

See <https://www.oxfordbibliographies.com/display/document/obo-9780199830060/obo-9780199830060-0016.xml> and <https://en.wikipedia.org/wiki/Life_history_theory> for a definition. I think that all case studies below fall in the LH category. I might consider moving the disease ecology case study in the main Sites and states chapter. See however  <https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.13681> for a link between disease ecology and life history theory. 

## Access to reproduction

@pradel1997

Transition matrix:
  
$$\begin{matrix}
& \\
\mathbf{\Gamma} =
  \left ( \vphantom{ \begin{matrix} 12 \\ 12 \\ 12 \\ 12 \\ 12 \end{matrix} } \right .
          \end{matrix}
          \hspace{-1.2em}
          \begin{matrix}
          z_t=J & z_t=1yNB & z_t=2yNB & z_t=B & z_t=D \\ \hdashline
          0 & \phi_1 (1-\alpha_1) & 0 & \phi_1 \alpha_1 & 1 - \phi_1\\
          0 & 0 & \phi_2 (1-\alpha_2) & \phi_2 \alpha_2 & 1 - \phi_2\\
          0 & 0 & 0 & \phi_3 & 1 - \phi_3\\
          0 & 0 & 0 & \phi_B & 1 - \phi_B\\
          0 & 0 & 0 & 0 & 1
          \end{matrix}
          \hspace{-0.2em}
          \begin{matrix}
          & \\
          \left . \vphantom{ \begin{matrix} 12 \\ 12 \\ 12 \\ 12 \\ 12 \end{matrix} } \right )
\begin{matrix}
z_{t-1} = J \\ z_{t-1} = 1yNB \\ z_{t-1} = 2yNB \\ z_{t-1} = B \\ z_{t-1} = D
\end{matrix}
\end{matrix}$$
  
First-year and second-year individuals breed with probabilities $\alpha_1$ and $\alpha_2$. Then, everybody breeds from age 3.

Observation matrix:
  
$$\begin{matrix}
& \\
\mathbf{\Omega} =
  \left ( \vphantom{ \begin{matrix} 12 \\ 12 \\ 12 \\ 12 \\12 \end{matrix} } \right .
          \end{matrix}
          \hspace{-1.2em}
          \begin{matrix}
          y_t = 1 & y_t = 2 & y_t = 3 & y_t = 4\\ \hdashline
          1 & 0 & 0 & 0\\
          1 - p_1 & p_1 & 0 & 0\\
          1 - p_2 & 0 & p_2 & 0\\
          1 - p_3 & 0 & 0 & p_3\\
          1 & 0 & 0 & 0
          \end{matrix}
          \hspace{-0.2em}
          \begin{matrix}
          & \\
          \left . \vphantom{ \begin{matrix} 12 \\ 12 \\ 12 \\ 12 \\12 \end{matrix} } \right )
\begin{matrix}
z_t = J \\ z_t = 1yNB \\ z_t = 2yNB \\ z_t = B \\ z_t = D
\end{matrix}
\end{matrix}$$

Juveniles are never detected.

## Tradeoffs {#casestudytradeoff}

@morano_life-history_2013, @shefferson_life_2003, and @cruz-flores_sex-specific_nodate

Case study with simulations as in Oikos paper, see Figure 1 and Table 2. Would be a nice example of the use of simulations. Another example could the statistical power analyses.

## Breeding dynamics

@pradel_breeding_2012, @desprez_now_2011, @desprez_known_2013, and @pacoureau_population_2019

## Using data on dead recoveries

### Ring recovery simple model

### Combination of live captures and dead recoveries

Combine live recapture w/ dead recoveries by @lebreton1999.

Transition matrix


$$\begin{matrix}
& \\
\mathbf{\Gamma} =
  \left ( \vphantom{ \begin{matrix} 12 \\ 12 \\ 12 \end{matrix} } \right .
          \end{matrix}
          \hspace{-1.2em}
          \begin{matrix}
          z_t=A & z_t=JD & z_t=D \\ \hdashline
          s & 1-s & 0\\
          0 & 0 & 1\\
          0 & 0 & 1
          \end{matrix}
          \hspace{-0.2em}
          \begin{matrix}
          & \\
          \left . \vphantom{ \begin{matrix} 12 \\ 12 \\ 12 \end{matrix} } \right )
\begin{matrix}
z_{t-1}=\text{alive} \\ z_{t-1}=\text{just dead} \\ z_{t-1}=\text{dead for good}
\end{matrix}
\end{matrix}$$


  
Observation matrix

$$\begin{matrix}
& \\
\mathbf{\Omega} =
  \left ( \vphantom{ \begin{matrix} 12 \\ 12 \\ 12\end{matrix} } \right .
          \end{matrix}
          \hspace{-1.2em}
          \begin{matrix}
          y_t=1 & y_t=2 & y_t=3 \\ \hdashline
          1 - p & 0 & p\\
          1 - r & r & 0\\
          1 & 0 & 0
          \end{matrix}
          \hspace{-0.2em}
          \begin{matrix}
          & \\
          \left . \vphantom{ \begin{matrix} 12 \\ 12 \\ 12 \end{matrix} } \right )
\begin{matrix}
z_{t}=A \\ z_{t}=JD \\ z_{t}=D
\end{matrix}
\end{matrix}$$


### Cause-specific mortalities

@koons2014, @fernandez-chacon_causes_2016 and @ruette_comparative_2015


## Stopover duration

@guerin_advances_2017 for a comparison of method, would be great to reproduce all analyses. 

## Actuarial senescence

@choquet_semi-markov_2011, @peron_evidence_2016 and @marzo2011.

## Uncertainty in age

E.g. @Gervasi2017.

## Uncertainty in age and size

E.g. @gowan2021uncertainty.
