---
title: "Curated list of papers using hidden Markov models to analyse capture-recapture data"
date: "last updated: `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(DT)

df <- data.frame(
  authors	= c("Barraquand & Nielsen",
    "Santostasi et al.",
            "Buzdugan et al.",
            "Laake et al.",
            "Conn & Cooch",
            "Cubaynes et al.",
            "Cole et al.",
            "Couet et al.",
            "Gimenez et al.",
            "Gimenez et al.",
            "Lagrange et al.",
            "Lebreton et al.",
            "Pradel",
            "Lunn et al.",
            "Pradel & Sanz-Aguilar",
            "Choquet et al.",
            "Cubaynes et al.",
            "Desprez et al.",
            "Genovart et al.",
            "Gervasi et al.",
            "Jennelle et al.",
            "Marescot et al.",
            "Pradel et al.",
            "Rouan et al.",
            "Sanz-Aguilar et al.",
            "Rouan et al.",
            "Santoro et al.",
            "Choquet et al.",
            "Berger et al.",
            "Culina et al.",
            "Sanz-Aguilar et al.",
            "Dupont et al.",
            "Culina et al.",
            "Fréville et al.",
            "Choquet et al.",
            "Koons et al.",
            "Robert et al.",
            "Guérin et al.",
            "Fernández‐Chacón",
            "Hernández-Matías",
            "Ruette et al.",
            "Hardouin et al.",
            "Etterson",
            "Pradel et al.",
            "Lorentzen et al.",
            "Desprez et al.",
            "Genovart et al.",
            "Payo-Payo et al.",
            "Chapple et al.",
            "Souchay et al.",
            "Chevallier et al.",
            "Cayuela et al.",
            "Avril et al.",
            "Cayuela et al.",
            "Fernández‐Chacón et al.",
            "Gourlay-Larour et al.",
            "Lagrange et al.",
            "Souchay et al.",
            "Barthold et al.",
            "Turek et al.",
            "Nater et al.",
            "Pluntz et al.",
            "Servanty et al.",
            "Besbeas & Morgan",
            "Glennie et al.",
            "Johnson et al.",
            "Rankin et al.",
            "Mews et al.",
            "Buckland et al.",
            "Choquet",
            "Choquet et al.",
            "King & Langrock",
            "Worthington et al.",
            "Langrock & King",
            "Cowen et al.",
            "Jeyam et al."),
  year = c(2021,
           2019,
         2017,
         2013,
         2009,
         2021,
         2014,
         2019,
         2018,
         2012,
         2017,
         2009,
         2005,
         2016,
         2012,
         2009,
         2010,
         2013,
         2012,
         2017,
         2007,
         2018,
         2007,
         2009,
         2011,
         2009,
         2014,
         2013,
         2016,
         2015,
         2015,
         2015,
         2013,
         2013,
         2011,
         2014,
         2015,
         2017,
         2015,
         2015,
         2014,
         2015,
         2013,
         2012,
         2012,
         2011,
         2016,
         2016,
         2016,
         2014,
         2012,
         2018,
         2012,
         2016,
         2017,
         2014,
         2014,
         2015,
         2016,
         2016,
         2020,
         2018,
         2010,
         2019,
         2019,
         2016,
         2016,
         2020,
         2004,
         2018,
         2017,
         2015,
         2019,
         2013,
         2017,
         2021),
  title = c('<a href="https://peerj.com/articles/12404/">Survival rates of adult and juvenile gyrfalcons in Iceland: estimates and drivers.</a>',
    '<a href="https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.4819">Use of hidden Markov capture–recapture models to estimate abundance in the presence of uncertainty: Application to the estimation of prevalence of hybrids in animal populations	hybridization	prevalence.</a>',
          '<a href="https://www.nature.com/articles/s41598-017-00806-4">Inference of the infection status of individuals using longitudinal testing data from cryptic populations: Towards a probabilistic approach to diagnosis	disease ecology	prevalence.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12065">marked: an R package for maximum likelihood and Markov Chain Monte Carlo analysis of capture–recapture data.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2664.2008.01597.x">Multistate capture–recapture analysis under imperfect state observation: an application to disease models.</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.7296">Modeling the demography of species providing extended parental care: A capture–recapture multievent model with a case study on polar bears (Ursus maritimus).</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/10.1002/ece3.1037">Does your species have memory? Analyzing capture‐recapture data with memory models.</a>',
          '<a href="https://doi.org/10.1002/ece3.5693">Joint estimation of survival and breeding probability in female dolphins and calves with uncertainty in state assignment.</a>',
          '<a href="https://doi.org/10.1111/oik.04532">Individual heterogeneity and capture‐recapture models: What, why and how?.</a>',
          '<a href="https://doi.org/10.1016/j.tpb.2012.02.001">Estimating demographic parameters using hidden process dynamic models.</a>',
          '<a href="https://doi.org/10.1002/ece3.3241">Assessment of individual and conspecific reproductive success as determinants of breeding dispersal of female tree swallows: A capture‐recapture approach.</a>',
          '<a href="https://www.sciencedirect.com/science/article/pii/S0065250409004036">Modeling individual animal histories with multistate capture‐recapture models.</a>',
          '<a href="https://doi.org/10.1111/j.1541-0420.2005.00318.x">Multievent: An extension of multistate capture–recapture models to uncertain states.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/10.1890/15-1256">Demography of an apex predator at the edge of its range: impacts of changing sea ice on polar bears in Hudson Bay.</a>',
          '<a href="https://doi.org/10.1371/journal.pone.0032666">Modeling Trap‐Awareness and related phenomena in capture‐recapture studies.</a>',
          '<a href="https://link.springer.com/chapter/10.1007/978-0-387-78151-8_39">Program E‐Surge: A software application for fitting multievent models.</a>',
          '<a href="https://doi.org/10.1111/j.1523-1739.2009.01431.x"> Importance of accounting for detection heterogeneity when estimating abundance: the case of French wolves.</a>',
          '<a href="https://doi.org/10.1002/ece3.846">Known unknowns in an imperfect world : incorporating uncertainty in recruitment estimates using multievent capture – recapture models.</a>',
          '<a href="https://doi.org/10.1111/j.1365-2656.2012.01991.x">Exploiting uncertain ecological fieldwork data with multievent capture – recapture modelling: an example with bird sex assignment.</a>',
          '<a href="https://doi.org/10.1007/s10144-017-0587-0">Estimating survival in the Apennine brown bear accounting for uncertainty in age classification.</a>',
          '<a href="https://doi.org/10.1890/1051-0761(2007)017[0154:SDPADP]2.0.CO;2">State specific detection probability and disease prevalence.</a>',
          '<a href="https://doi.org/10.1111/1365-2435.13059/epdf"> Social status mediates the fitness costs of infection with canine distemper virus in Serengeti spotted hyenas.</a>',
          '<a href="https://doi.org/10.1002/cjs.5550360105">Estimation of sex‐specific survival with uncertainty in sex assessment.</a>',
          '<a href="https://link.springer.com/chapter/10.1007/978-0-387-78151-8_40">Estimation of lifetime reproductive success when reproductive status cannot always be assessed.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/09-2339.1?sid=nlm%3Apubmed">Studying the reproductive skipping behavior in long‐lived birds by adding nest inspection to individual‐based data.</a>',
          '<a href="https://link.springer.com/article/10.1198/jabes.2009.06108">A general framework for modeling memory in capture‐recapture data.</a>',
          '<a href="https://veterinaryresearch.biomedcentral.com/articles/10.1186/1297-9716-45-39">Multi-event capture–recapture modeling of host–pathogen dynamics among European rabbit populations exposed to myxoma and Rabbit Hemorrhagic Disease Viruses: common and heterogeneous patterns.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/10.1890/12-1849.1">Estimating transitions between states using measurements with imperfect detection: application to serological data.</a>',
          '<a href="https://academic.oup.com/jmammal/article/97/3/992/2459827"> Age-specific survival in the socially monogamous alpine marmot ( Marmota marmota ): evidence of senescence.</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/jav.00661">Evidence of a link between survival and pair fidelity across multiple tit populations.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/14-0437.1">Multi‐event capture–recapture analysis reveals individual foraging specialization in a generalist species.</a>',
          '<a href="https://link.springer.com/article/10.1007%2Fs00442-015-3375-6">Litter sex composition influences dominance status of Alpine marmots (Marmota marmota).</a>',
          '<a href=https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.729"">A multievent approach to estimating pair fidelity and heterogeneity in state transitions.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2745.12141">Inferring seed bank from hidden Markov models: new insights into metapopulation dynamics in plants.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/10.1111/j.2041-210X.2011.00088.x">A semi‐Markov model to assess reliably survival patterns from birth to death in free‐ranging populations.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12239">Methods for studying cause‐specific senescence in the wild.</a>',
          '<a href="https://royalsocietypublishing.org/doi/full/10.1098/rspb.2015.1529">The survival–reproduction association becomes stronger when conditions are good.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/eap.1551">Advances in methods for estimating stopover duration for migratory species using capture–recapture data.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.12477">Demographic effects of full vs. partial protection from harvesting: inference from an empirical before–after control‐impact study on Atlantic cod.</a>',
          '<a href="https://www.sciencedirect.com/science/article/abs/pii/S0006320715002517?via%3Dihub">Electrocution threatens the viability of populations of the endangered Bonellis eagle (Aquila fasciata) in Southern Europe.</a>',
          '<a href="https://zslpublications.onlinelibrary.wiley.com/doi/abs/10.1111/jzo.12201">Comparative survival pattern of the syntopic pine and stone martens in a trapped rural area in France.</a>',
          '<a href="https://zslpublications.onlinelibrary.wiley.com/doi/abs/10.1111/acv.12196">Survival and movement of translocated houbara bustards in a mixed conservation area.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/10.1890/12-1166.1">Hidden Markov models for estimating animal mortality from anthropogenic hazards.</a>',
          '<a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0051016">Breeding Experience Might Be a Major Determinant of Breeding Probability in Long-Lived Species: The Case of the Greater Flamingo.</a>',
          '<a href="https://link.springer.com/article/10.1007/s10336-011-0723-0">Modelling state uncertainty with photo series data for the estimation of breeding success in a cliff-nesting seabird.</a>',
          '<a href="https://royalsocietypublishing.org/doi/10.1098/rspb.2011.0189">Now you see him, now you do not: experience, not age, is related to reproduction in kittiwakes.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.12622">Demography of the critically endangered Balearic shearwater: the impact of fisheries and time to extinction.</a>',
          '<a href="https://royalsocietypublishing.org/doi/full/10.1098/rspb.2015.3042">Consecutive cohort effects driven by density-dependence and climate influence early-life survival in a long-lived bird.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.1589">A novel application of multi‐event modeling to estimate class segregation in a highly migratory oceanic vertebrate.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/13-1277.1">To breed or not: a novel approach to estimate breeding propensity and potential trade‐offs in an Arctic‐nesting species.</a>',
          '<a href="https://zslpublications.onlinelibrary.wiley.com/doi/abs/10.1111/j.1469-1795.2012.00584.x">Use of mixture models to characterize site quality in philopatric animals: a case study with Bonellis eagle.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecy.2195">Estimating dispersal in spatiotemporally variable environments using multievent capture–recapture modeling.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/11-1742.1">A multi‐event model to study stage‐dependent dispersal in radio‐collared hares: when hunting promotes costly transience.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12717">Analysing movement behaviour and dynamic space‐use strategies among habitats using multi‐event capture‐recapture modelling.</a>',
          '<a href="https://cdnsciencepub.com/doi/abs/10.1139/cjfas-2015-0313">Causes of mortality in depleted populations of Atlantic cod estimated from multi-event modelling of mark–recapture and recovery data.</a>',
          '<a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0096478">Movement Patterns in a Partial Migrant: A Multi-Event Capture-Recapture Approach.</a>',
          '<a href="https://esajournals.onlinelibrary.wiley.com/doi/10.1890/13-1564.1">Estimating dispersal among numerous sites using capture–recapture data.</a>',
          '<a href="https://wildlife.onlinelibrary.wiley.com/doi/abs/10.1002/jwmg.879">Absence of difference in survival between two distant breeding sites of greater snow geese.</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/10.1002/ece3.2247">Dead or gone? Bayesian inference on mortality for the dispersing sex.</a>',
          '<a href="https://link.springer.com/article/10.1007/s10651-016-0353-z">Efficient Markov chain Monte Carlo sampling for hierarchical hidden Markov models.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2656.13269">Size‐ and stage‐dependence in cause‐specific mortality of migratory brown trout.</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/ele.13097">A general method for estimating seed dormancy and colonisation in annual plants from the observation of existing flora.</a>',
          '<a href="https://doi.org/10.1890/09-1931.1">Assessing whether mortality is additive using marked animals: A Bayesian state–space modeling approach.</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/biom.13045">Exact inference for integrated population modelling.</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/10.1111/biom.13078">Open population maximum likelihood spatial capture‐recapture.</a>',
          '<a href="https://projecteuclid.org/journals/statistical-science/volume-31/issue-2/Multivariate-State-Hidden-Markov-Models-for-Mark-Recapture-Data/10.1214/15-STS542.full">Multivariate State Hidden Markov Models for Mark-Recapture Data.</a>',
          '<a href="https://www.frontiersin.org/articles/10.3389/fmars.2016.00025/full">A Full-Capture Hierarchical Bayesian Model of Pollocks Closed Robust Design and Application to Dolphins.</a>',
          '<a href="https://arxiv.org/abs/2002.10997">Continuous-time multi-state capture-recapture models.</a>',
          '<a href="https://www.sciencedirect.com/science/article/abs/pii/S0304380003003302">State-space models for the dynamics of wild animal populations.</a>',
          '<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12961">Markov‐modulated Poisson processes as a new framework for analysing capture–recapture data.</a>',
          '<a href="https://www.sciencedirect.com/science/article/abs/pii/S030438001730354X">Transient state estimation using continuous-time processes applied to opportunistic capture–recapture data.</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/full/10.1111/biom.12446">Semi‐Markov Arnason–Schwarz models.</a>',
          '<a href="https://projecteuclid.org/journals/annals-of-applied-statistics/volume-13/issue-4/Estimating-abundance-from-multiple-sampling-capture-recapture-data-via-a/10.1214/19-AOAS1264.short">Estimating abundance from multiple sampling capture-recapture data via a multi-state multi-period stopover model.</a>',
          '<a href="https://projecteuclid.org/journals/annals-of-applied-statistics/volume-7/issue-3/Maximum-likelihood-estimation-of-markrecapturerecovery-models-in-the-presence-of/10.1214/13-AOAS644.full">Maximum likelihood estimation of mark–recapture–recovery models in the presence of continuous covariates.</a>',
          '<a href="https://onlinelibrary.wiley.com/doi/pdf/10.1111/biom.12701">Hidden Markov Models for Extended Batch Data.</a>',
          '<a href="https://www.frontiersin.org/articles/10.3389/fevo.2021.598325/full">A Test for the Underlying State-Structure of Hidden Markov Models: Partially Observed Capture-Recapture Data.</a>'),
  ecological_topic = c("survival",
    "hybridization",
                     "disease ecology",
                     "survival",
                     "disease ecology",
                     "family structure",
                     "dispersal",
                     "recruitment",
                     "individual heterogeneity",
                     "recruitment",
                     "dispersal",
                     "demography",
                     "dispersal",
                     "survival",
                     "survival",
                     "demography",
                     "abundance",
                     "recruitment",
                     "survival",
                     "survival",
                     "disease ecology",
                     "disease ecology",
                     "survival",
                     "fitness",
                     "reproductive skipping",
                     "dispersal",
                     "disease ecology",
                     "disease ecology",
                     "actuarial senescence",
                     "survival",
                     "foraging strategies",
                     "dominance",
                     "survival",
                     "seed bank",
                     "senescence",
                     "senescence",
                     "trade-offs",
                     "stop-over duration",
                     "cause-specific mortalities",
                     "survival",
                     "survival",
                     "movements",
                     "survival",
                     "breeding propensity",
                     "survival",
                     "recruitment",
                     "survival",
                     "survival",
                     "temporary emigraphy",
                     "breeding propensity",
                     "survival",
                     "dispersal",
                     "dispersal",
                     "dispersal",
                     "cause-specific mortalities",
                     "migration",
                     "dispersal",
                     "survival",
                     "survival",
                     "dispersal",
                     "cause-specific mortalities",
                     "metapopulation dynamics",
                     "cause-specific mortalities",
                     "population dynamics",
                     "population dynamics",
                     "survival",
                     "population dynamics",
                     "dispersal",
                     "population dynamics",
                     "survival",
                     "survival",
                     "dispersal",
                     "stop-over duration",
                     "individual time-varying covariates",
                     "population dynamics",
                     "dispersal"),
  methodological_keyword = c("live-recapture and dead-recovery combination",
                           "prevalence",
                           "prevalence",
                           "software",
                           "state uncertainty",
                           "state uncertainty",
                           "memory",
                           "state uncertainty",
                           "heterogeneity",
                           "state uncertainty",
                           "state uncertainty",
                           "multistate",
                           "state uncertainty",
                           "multistate",
                           "trap-dependence",
                           "software",
                           "finite mixtures",
                           "state uncertainty",
                           "sex assignment",
                           "age uncertainty",
                           "prevalence",
                           "state uncertainty",
                           "sex uncertainty",
                           "viterbi",
                           "indirect information",
                           "memory",
                           "state uncertainty",
                           "continuous measurement",
                           "state uncertainty",
                           "state uncertainty",
                           "state uncertainty",
                           "state uncertainty",
                           "dependence",
                           "metapopulation",
                           "semi-Markov",
                           "cause-specific mortalities",
                           "state uncertainty",
                           "semi-Markov",
                           "live-recapture and dead-recovery combination",
                           "cause-specific mortalities",
                           "live-recapture and dead-recovery combination",
                           "live-recapture and dead-recovery combination",
                           "state uncertainty",
                           "state uncertainty",
                           "state uncertainty",
                           "state uncertainty",
                           "live-recapture and dead-recovery combination",
                           "live-recapture and dead-recovery combination",
                           "combination of information",
                           "robust-design",
                           "finite mixtures",
                           "state uncertainty",
                           "radio-collared individuals",
                           "state uncertainty",
                           "live-recapture and dead-recovery combination",
                           "live-recapture and dead-recovery combination",
                           "state uncertainty",
                           "live-recapture and dead-recovery combination",
                           "sex uncertainty",
                           "software",
                           "state uncertainty",
                           "state uncertainty",
                           "multistate",
                           "integrated population model",
                           "spatial explicit capture-recapture",
                           "multivariate model",
                           "robust-design",
                           "continuous time",
                           "state-space models",
                           "continuous time",
                           "continuous time",
                           "semi-Markov",
                           "robust-design",
                           "missing data",
                           "batch marking",
                           "goodness-of-fit tests"

)) %>%
  mutate(ecological_topic = as_factor(ecological_topic),
         methodological_keyword = as_factor(methodological_keyword))
#df <- readxl::read_xlsx(here::here("slides", "dat", "papers.xlsx")) 
```


```{r echo = FALSE}
datatable(data = df, 
#          filter = 'top', 
          escape = 3, 
          options = list(#columnDefs = list(list(targets = c(1,2,3), searchable = FALSE)),
                         autoWidth = TRUE,
                         scrollX = TRUE,
                         initComplete = JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#88127C', 'color': '#fff'});",
    "}")))
```

