# Covariates {#covariateschapter}

## Missing values

Work on missing values by @bonner2006 (see @gimenez2009winbugs) and @langrock2013maximum and @worthington2015. See also @rose2018.

## Nonlinearities

Splines à la @gimenez_semiparametric_2006, possibly w/ jagam <https://rdrr.io/cran/mgcv/src/R/jagam.r>. 

## Covariate selection

RJMCMC in @gimenez2009fitness on Common blackbirds or @gimenez2009winbugs on White stork.

As an illustration, we use data on the white stork {\it Ciconia ciconia} population in Baden W\"{u}rttemberg (Germany), consisting of 321 capture histories of individuals ringed as chicks between 1956 and 1971. From the 60's to the 90's, all Western European stork populations were declining @bair91. This trend was likely the result of reduced food availability @schau05 caused by severe droughts observed in the wintering ground of storks in the Sahel region. This hypothesis has been examined in several studies (@kanya90 and @barb99). 

Check out <https://r-nimble.org/nimbleExamples/RJMCMC_example.html>.

## Sex uncertainty

@pradel2008sex and @genovart_exploiting_2012

## Actuarial senescence

@choquet_semi-markov_2011, @peron_evidence_2016 and @marzo2011.

## Covariate on multinomial logit link or Dirichlet

Example?

## Uncertainty in age

E.g. @Gervasi2017.

## Spatial

Not spatial capture-recapture sensu SCR or SECR or oSCR. Refer to book.

3D Splines as in @Peron2011. (I)CAR as in @saracco2010icar (see  (<https://github.com/Andrew9Lawson/Bayesian-DM-code-examples> and <https://r-nimble.org/html_manual/cha-spatial.html> for NIMBLE implementation). Add RSR @khan2022rsr (see Jags code at <https://gist.github.com/oliviergimenez/0d5519654adef09060581eb49e2128ce>). 
