--- 
title: "Bayesian Analysis of Capture-Recapture Data with Hidden Markov Models – Theory and Case Studies in R"
author: "Olivier Gimenez"
date: "`r Sys.Date()`"
documentclass: krantz
bibliography: [book.bib]
#biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
fontsize: 12pt
site: bookdown::bookdown_site
description: "This is a textbook on the analysis of capture-recapture data with hidden Markov models (HMM) implemented in the Bayesian framework with R."
url: 'https\://oliviergimenez.github.io/bayesian-cr-workshop/'
github-repo: oliviergimenez/banana-book
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \usepackage{blkarray}
---


```{r setup, include=FALSE}
options(
#  htmltools.dir.version = FALSE, 
  formatR.indent = 2,
  width = 55, 
  digits = 4, 
  warnPartialMatchAttr = FALSE, 
  warnPartialMatchDollar = FALSE
)
```

# Welcome {-}

Welcome to the online version of the book *Bayesian Analysis of Capture-Recapture Data with Hidden Markov Models – Theory and Case Studies in R*. <!-- The book is also available in [PDF format](https://github.com/oliviergimenez/banana-book/raw/master/docs/bayesHMMcapturerecapture.pdf). -->

The HMM framework has gained much attention in the ecological literature over the last decade, and has been suggested as a general modelling framework for the demography of plant and animal populations. In particular, HMMs are increasingly used to analyse capture-recapture data and estimate key population parameters (e.g., survival, dispersal, recruitment or abundance) with applications in all fields of ecology. 

In parallel, Bayesian statistics is well established and fast growing in ecology and related disciplines, because it resonates with scientific reasoning and allows accommodating uncertainty smoothly. The popularity of Bayesian statistics also comes from the availability of free pieces of software (WinBUGS, OpenBUGS, JAGS, Stan, NIMBLE) that allow practitioners to code their own analyses.

This book offers a Bayesian treatment of HMMs applied to capture-recapture data. You will learn to use the R package NIMBLE which is seen by many as the future of Bayesian statistical ecology to deal with complex models and/or big data. An important part of the book consists in case studies presented in a tutorial style to abide by the “learning by doing” philosophy.

I'm currently writing this book, and I welcome any feedback `r emo::ji("innocent")` by raising an issue [here](https://github.com/oliviergimenez/banana-book/issues), amending directly the R Markdown file that generated the page you're reading by clicking on the 'Edit this page' icon in the right panel, or via [email](mailto:olivier.gimenez@cefe.cnrs.fr). Many thanks!

Olivier Gimenez, Montpellier, France  
Last updated: `r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%B %d, %Y")`

## License {-}

The online version of this book is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License](http://creativecommons.org/licenses/by-nc-nd/4.0/). 

The code is public domain, licensed under [Creative Commons CC0 1.0 Universal (CC0 1.0)](https://creativecommons.org/publicdomain/zero/1.0/).

