# Miscelleanous {#misc}

## Dependence among individuals

@culina_multievent_2013 and @cubaynes_modeling_2021

## Cause-specific mortalities

@fernandez-chacon_causes_2016 and @ruette_comparative_2015

## Disease dynamics

@MarescotEtAl2018 and @santoro_multi-event_2014. House finch as well.

## Combine live captures and dead recoveries

Combine live recapture w/ dead recoveries by [Lebreton et al. (1999)](https://www.tandfonline.com/doi/pdf/10.1080/00063659909477230) and go spatial to account for emigration [Gilroy et al. (2012)](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/12-0124.1) and [Schaub & Royle (2014)](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12134).

##  Stopover duration

A voir? Papier de Guerin et al. (2017)

## Prior info

Papier McCarthy and Pipper. Cf le code et tout dans le fichier leftover. Ajouter figure avec 3, 4 et 5 ans seulement. 

The example on how to incorporate prior information is in [McCarthy and Masters (2005)](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/j.1365-2664.2005.01101.x).

## Posterior predictive check

M-array avec Paganin et de Valpine. Puis IH avec Chambert. Et aussi geometric avec Conn et al. 

## Others

Multispecies. Phylogeny. Path analysis, SEM. Exemple Nina loup hybrides, ou prévalence disease, ou sex-ratio, ou la LRS comme dans papier TPB. Manque sûrement qqch sur l'intérêt des simulations, en faire un CS? Vérifier que les posterior predictive checks sont traités quelque part.

